requires 'Path::Tiny';
requires 'Object::Simple';
requires 'Cpanel::JSON::XS';
requires 'Template::Semantic';
requires 'HTML::Packer';
requires 'DateTime';
requires 'DateTime::Format::Strptime';
requires 'XML::Feed';
requires 'IPC::Run';
