requires 'Mojolicious';
requires 'Text::WikiCreole';
requires 'DateTime::Format::ISO8601';
requires 'HTML::Packer';
requires 'HTML::Escape';
requires 'String::Util';
requires 'YAML';
requires 'XML::Feed';
requires 'HTML5::DOM'
