#!/usr/bin/env perl
use Mojolicious::Lite -signatures;
use Mojo::File 'path';
use YAML;

sub get_meta {
  my $file = shift;
  my $content = $file->slurp;

  my ($meta, $_excerpt, $_body) = Load($content);
  return {
    title => $meta->{title},
    slug => $meta->{slug},
    created_at => $meta->{created_at}
  };
}

sub all_posts {
  my $path = path('../site/posts');
  my @posts = $path
    ->list({dir => 1})
    ->map(\&get_meta);
  return @posts;
}

sub get_post {
  my $slug = shift;
  my $file = path('../site/posts/' . $slug . '.yml');
  my $content = $file->slurp;

  my ($meta, $excerpt, $body) = Load($content);

  return {
    title => $meta->{title},
    content => $body,
    excerpt => $excerpt
  };
}

get '/' => 'index';
get '/edit' => 'edit';

get '/posts/:slug' => sub ($c) {
  my $slug = $c->param('slug');

  $c->render(json => get_post($slug));
};

get '/posts' => sub ($c) {
  my @listdir = all_posts;

  my $resp = {
    posts => @listdir
  };

  $c->render(json => $resp);
};

app->start;
